config/routes.rb
Swiki::Application.routes.draw do
  get "charges/create"
  get "charges/new"
  devise_for :users
  resources :wikis do
    resources :collabs #, except: [:index]
  end
  resources :charges, only: [:create, :new]

  

  root 'welcome#index'

end

app/models/collab.rb
class Collab < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

  def self.collab_id(wiki, user)
    Collab.where(wiki_id: wiki.id).where(user_id: user.id).first.id    
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_many :collabs, dependent: :destroy       
  has_many :wikis, through: :collabs

  before_destroy :reassign_wikis, prepend: true

  scope :owner_by_wiki, -> (wiki_id){
    User.joins(:collabs).where("collabs.wiki_id = ?", wiki_id).where("collabs.owner = ?", true).first    
  }

  scope :current_collaborators, -> (wiki_id){
    User.joins(:collabs).where("collabs.wiki_id = ?", wiki_id).where("collabs.owner = ?", false)
  }
  
  def role?(base_role)
    role == base_role.to_s
  end

  private

  def reassign_wikis
    admin = User.where(role: "admin").first
    user_wikis = Wiki.by_user_wikis(self.id)

    user_wikis.update_all( public: true) 

    # Wiki.update(user_wikis.ids, {public: true})
    user_wikis.each do |wiki|
      wiki.remove_collabs
    end
    
    self.collabs.where(owner: true).update_all(user_id: admin.id)
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :collabs, dependent: :destroy
  has_many :users, through: :collabs
  has_one :owner_collab, -> {where("owner = ?", true)}, class_name: "Collab"
  has_one :owner, through: :owner_collab, source: :user

  after_update :remove_collabs, if: :public_wiki?

  extend FriendlyId
  friendly_id :title, use: :slugged

  scope :grouped_collabs, -> { joins(:collabs).group("collabs.wiki_id")}

  scope :by_user_collabs, -> (id){
    Wiki.joins(:collabs).where("collabs.user_id = ?",id).where("collabs.owner = ?", false)
  }

  scope :by_user_wikis, -> (id){
    Wiki.joins(:collabs).where("collabs.user_id = ?", id).where("collabs.owner = ?", true)
  }

  def remove_collabs
    self.collabs.where(owner: false).delete_all
  end

  def public_wiki?
    self.public == true
  end

  def self.create_wiki_seed(user, title, public = true)
    newwiki = Wiki.new(
      title: title,
      body: "This is a #{title} article.",
      public: public
    )
    newwiki.save

    newcollab = Collab.new(
      user_id: user.id,
      wiki_id: newwiki.id,
      owner: true
    )
    newcollab.save  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to (request.referrer || root_path)
    # redirect_to root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  # after_action :user_to_premium, only: :create

  def create
    
    authorize :charge, :create?
    @amount = params[:amount]

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: "Swiki Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    flash[:notice] = "Welcome to Swiki Premium Membership, #{current_user.email}!"
    user_to_premium
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  def new
    authorize :charge, :new?
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key]}",
      description: "Swiki Premium Membership - #{current_user.email}",
      amount: 2_99
    }
  end

  private

  def user_to_premium
    current_user.update_attribute(:role, "premium")    
  end
end

app/controllers/collabs_controller.rb
class CollabsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: :index
  # after_action :verify_policy_scoped, only: :index


  def index
    @wiki = Wiki.friendly.find(params[:wiki_id])
    authorize @wiki, :show_collabs?
    @owner = User.owner_by_wiki(@wiki.id)
    @current = User.current_collaborators(@wiki.id)
    @available = User.where.not(id: @owner.id) - @current.to_a
  end

  def create
    @wiki = Wiki.friendly.find(params[:wiki_id])
    authorize @wiki, :collab_add_remove?
    @collab = Collab.new(collab_params)
    authorize @collab

    if @collab.save
      redirect_to wiki_collabs_path, notice: 'Collaborator successfully added.'
    else
      redirect_to wiki_collabs_path, notice: 'Error adding collaborator.'
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:wiki_id])
    authorize @wiki, :collab_add_remove?

    @collab = Collab.find(params[:id])

    if @collab.destroy
      redirect_to wiki_collabs_path, notice: 'Collaborator successfully removed.'
    else
      redirect_to wiki_collabs_path, notice: 'Error removing collaborator.'
    end
  end

  private

  def collab_params
    params.require(:collab).permit(:owner, :user_id, :wiki_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  after_action :verify_authorized, except: :index
  # after_action :verify_policy_scoped, only: :index


  def index
    case params[:option]
    when "mine"
      authenticate_user!
      @my_wikis = Wiki.by_user_wikis(current_user.id)
      @collab_wikis = Wiki.by_user_collabs(current_user.id)
      render "my_wiki"
    else
      # Wiki.all for admin, Wiki.where(public: true) for all others
      @wikis = policy_scope(Wiki) 
      # @wikis = Wiki.where(public: true)
      @collabs_count = Wiki.grouped_collabs.count
    end
  end

  def show
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
    @switch = "new"
  end

  def edit
    authorize @wiki
    @switch = "edit"
  end

  def create
    @wiki = Wiki.new(wiki_params)
    authorize @wiki
    @collab = @wiki.collabs.build(
      owner: true,
      user_id: current_user.id
    )

    if @wiki.save #&& @collab.save
      redirect_to @wiki, notice: 'Wiki was successfully created.'
    else
      render action: 'new' 
    end
  end

  def update
    authorize @wiki
    if @wiki.update(wiki_params)
      case params[:option]
      when "fromlink"
        redirect_to :back
      else
        redirect_to @wiki, notice: 'Wiki was successfully updated.'
      end
    else
      render action: 'edit'
    end
  end

  def destroy
    authorize @wiki
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to wikis_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.friendly.find(params[:id])

      rescue ActiveRecord::RecordNotFound
        flash[:error] = "Record not found."
        redirect_to root_path 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :public)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    render_options = {filter_html: true}
    renderer = Redcarpet::Render::HTML.new(render_options)

    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new( renderer, extensions)

    redcarpet.render(text).html_safe

  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collabs_helper.rb
module CollabsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.haml
%h1 Charges#create
%p Find me in app/views/charges/create.html.haml

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <%= hidden_field_tag :amount, @stripe_btn_data[:amount] %>
 
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
    data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> 
    data-description="<%= @stripe_btn_data[:description] %>" 
    data-email="<%= current_user.email %>"></script>
 <% end %>

app/views/collabs/index.html.haml
%h4 
  Wiki Owner:
= @owner.name
= @owner.email

%h4 Current Collaborators
- @current.each do |user|
  = user.name
  = user.email
  - if policy(@wiki).collab_add_remove?
    = link_to "Remove", wiki_collab_path(@wiki, id: Collab.collab_id(@wiki, user)), method: :delete
  %br

%h4 Available Collaborator
- @available.each do |user|
  = user.name
  = user.email
  - if policy(@wiki).collab_add_remove?
    = link_to "Add", wiki_collabs_path(@wiki, :collab => {owner: false, wiki_id: @wiki.id, user_id: user.id}), method: :post
  %br

app/views/collabs/show.html.haml
%h2 Collabs show

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Swiki
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          .navbar-brand= link_to 'Swiki', root_path
        %ul.nav.navbar-nav
          %li= link_to 'Wikis', wikis_path
          - if current_user
            %li= link_to 'My Wikis', wikis_path(option: "mine")
        %ul.nav.navbar-nav.navbar-right
          - if current_user
            %li= link_to "#{current_user.name} | #{current_user.role.capitalize} Account", edit_user_registration_path
            - if policy(:charge).new?
              %li= link_to "Upgrade!", new_charge_path
            %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'Sign In', new_user_session_path
            %li= link_to 'Register', new_user_registration_path

    .container
      - if flash[:notice]
        .alert.alert-success{:role => "alert"}
          = flash[:notice]
      - elsif flash[:error]
        .alert.alert-danger{:role => "alert"}
          = flash[:error]
      - elsif flash[:alert]
        .alert.alert-warning{:role => "alert"}
          = flash[:alert]

      = yield

app/views/layouts/backup_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swiki</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">

  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml

app/views/wikis/_form.html.haml
= form_for @wiki do |f|
  - if @wiki.errors.any?
    #error_explanation
      %h2= "#{pluralize(@wiki.errors.count, "error")} prohibited this wiki from being saved:"
      %ul
        - @wiki.errors.full_messages.each do |msg|
          %li= msg

  .col-md-8
    .form-group
      = f.label :title
      = f.text_field :title, class: "form-control"
    .form-group
      = f.label :body
      = f.text_area :body, rows: 12, class: "form-control", placeholder: "You can use Markdown syntax to edit wiki."
    - case @switch when "edit"
      - if policy(@wiki).make_private_edit?
        .form-group
          = f.label :public
          = f.check_box :public
    - when "new"
      - if policy(@wiki).make_private_new?
        .form-group
          = f.label :public
          = f.check_box :public
    - else

    .form-group
      = f.submit 'Save', class: "btn btn-primary"

  .col-md-4
    %h4 Wiki syntax rules:
    %ul
      %li Hit Enter twice for line breaks 
      %li No raw HTML allowed
      %li
        = link_to 'Markdown syntax guide', 'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'

app/views/wikis/edit.html.haml
%h3 Edit wiki

.row
  = render 'form'

.row
  .col-md-8
    = link_to 'Show', @wiki
    \|
    = link_to 'Back', wikis_path

app/views/wikis/index.html.haml
%h1 Listing wikis

%table.table
  %thead
    %tr
      %th Title
      %th Body
      - if current_user.present? && current_user.role?(:admin)
        %th Author
        %th Visibility
      %th Options

  - @wikis.each do |wiki|
    %tr
      %td= wiki.title
      %td= truncate(strip_tags(markdown(wiki.body)), length: 50)
      - if current_user.present? && current_user.role?(:admin)
        %td
          = wiki.owner.name
          |
          = link_to wiki_collabs_path(wiki) do
            Collaborators
            %span.badge
              = (@collabs_count[wiki.id] - 1)
        %td
          - if wiki.public
            Public
          - else
            Private
          = link_to 'Destroy', wiki, class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: 'Are you sure?'}
      %td
        = link_to 'Show', wiki
        - if current_user
          = link_to 'Edit', edit_wiki_path(wiki)

%br

= link_to 'New Wiki', new_wiki_path

app/views/wikis/my_wiki.html.haml
%h4 My Wikis

%table.table
  %thead
    %tr
      %th Title
      %th Body
      %th Visibility
      %th
      %th Options

  - @my_wikis.each do |wiki|
    %tr
      %td= wiki.title
      %td= truncate(strip_tags(markdown(wiki.body)), length: 50)
      - if wiki.public == true
        %td 
          Public
          - if policy(wiki).make_private_edit?
            = link_to 'Make Private', wiki_path(wiki, :wiki => {public: false}, option: "fromlink"), method: :put
      - else
        %td 
          Private
          - if policy(wiki).make_private_edit?
            = link_to 'Make Public', wiki_path(wiki, :wiki => {public: true}, option: "fromlink"), method: :put
      %td
        = link_to wiki_collabs_path(wiki) do
          Collaborators
          %span.badge
            = (wiki.collabs.count - 1)
      %td
        = link_to 'Show', wiki
        = link_to 'Edit', edit_wiki_path(wiki)
        = link_to 'Destroy', wiki, :method => :delete, :data => { :confirm => 'Are you sure?' }

%h4 My Collaborations

%table.table
  %thead
    %tr
      %th Title
      %th Body
      %th
      %th Options

  - @collab_wikis.each do |wiki|
    %tr
      %td= wiki.title
      %td= wiki.body
      %td
        = link_to wiki_collabs_path(wiki) do
          Collaborators
          %span.badge
            = (wiki.collabs.count - 1)
      %td
        = link_to 'Show', wiki
        = link_to 'Edit', edit_wiki_path(wiki)

app/views/wikis/new.html.haml
%h3 New wiki

.row
  = render 'form'

.row
  .col-md-8
    = link_to 'Back', wikis_path

app/views/wikis/show.html.haml
.row
  .col-md-8
    = link_to 'Edit', edit_wiki_path(@wiki)
    \|
    = link_to 'Back', :back
    %h3 
      Title:
      = @wiki.title
    %p
      %h3 Body:
      = markdown( @wiki.body )